
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
- stage: QADeploy
  dependsOn: Build 
  jobs:
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
- stage: UATDeploy
  dependsOn: Build 
  jobs:
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
- stage: ProdDeploy
  dependsOn:
  - Build
  - QADeploy
  - UATDeploy
  jobs:
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
  

 
