trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  variables:
    environment: Build 
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
    - bash: $(PipelineLevelVariable)
    - bash: $(environment)Stage
- stage: DevDeploy
  variables:
    environment: Dev 
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
    - bash: $(environment)Stage
- stage: UATDeploy4
  variables:
    environment: UAT
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
    - bash: $(environment)Stage
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn:
  - Build
  - DevDeploy
  - UATDeploy4
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
    - bash: $(environment)Stage