trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
- stage: UATDeploy4
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob
- stage: ProdDeploy
  dependsOn:
  - Build
  - DevDeploy
  - UATDeploy4
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build FirstJob