trigger:
- main

# strategy:
#   matrix:
#      linux: 
#       operatingSystem: 'ubuntu-latest'
#      mac: 
#       operatingSystem: 'macos-latest'        

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build 
    jobs: 
      - job: BuildJob
        steps:
          - bash: echo "Do the build"
  - stage: DevDeploy 
    jobs:   
      - deployment: DEVDeployJob
        environment: DEV
        strategy:
          runOnce: 
             deploy:
               steps:
                 - script: echo deploy to dev
  - stage: QADeploy 
    jobs:   
      - deployment: QADeployJob
        environment: QA
        strategy:
          runOnce: 
             deploy:
               steps:
                 - script: echo deploy to QA with approvals        
             


# steps:
# - script: echo Hello, OS $(operatingSystem)
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
